export type Phone = {
  id: number;
  brand: string;
  model: string;
  slug: string;
  price: number;
  os: string;
  releaseYear: number;
  createdAt: Date;
  updatedAt: Date;
};

export type Phones = Phone[];

export const dataPhones: Phones = [
  {
    id: 1,
    brand: "Apple",
    model: "iPhone 17",
    slug: "iphone-17",
    price: 1299,
    os: "iOS 19",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    brand: "Apple",
    model: "iPhone 17 Pro",
    slug: "iphone-17-pro",
    price: 1599,
    os: "iOS 19",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    brand: "Samsung",
    model: "Galaxy S25",
    slug: "galaxy-s25",
    price: 1099,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    brand: "Samsung",
    model: "Galaxy S25 Ultra",
    slug: "galaxy-s35-ultra",
    price: 1499,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    brand: "Huawei",
    model: "Mate 70 Pro",
    slug: "mate-70-pro",
    price: 999,
    os: "HarmonyOS 6",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    brand: "Huawei",
    model: "P80",
    slug: "p80",
    price: 899,
    os: "HarmonyOS 6",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    brand: "OPPO",
    model: "Find X8",
    slug: "find-x8",
    price: 899,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    brand: "OPPO",
    model: "Reno 13 Pro",
    slug: "reno-13-pro",
    price: 599,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    brand: "Realme",
    model: "Realme GT 7",
    slug: "realme-gt-7",
    price: 699,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    brand: "Realme",
    model: "Realme 14 Pro",
    slug: "realme-14-pro",
    price: 549,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    brand: "Vivo",
    model: "Vivo X120",
    slug: "vivo-x120",
    price: 999,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    brand: "Vivo",
    model: "Vivo V35",
    slug: "vivo-v35",
    price: 499,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    brand: "IQOO",
    model: "IQOO 14",
    slug: "iqoo-14",
    price: 799,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    brand: "IQOO",
    model: "IQOO Neo 10",
    slug: "iqoo-neo-10",
    price: 499,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    brand: "Tecno",
    model: "Tecno Phantom X4",
    slug: "techno-phantom-x4",
    price: 599,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    brand: "Tecno",
    model: "Tecno Spark 15",
    slug: "techno-spark-15",
    price: 199,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    brand: "Infinix",
    model: "Infinix Zero 40",
    slug: "infinix-zero-40",
    price: 399,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    brand: "Infinix",
    model: "Infinix Note 15",
    slug: "infinix-note-15",
    price: 249,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    brand: "Itel",
    model: "Itel Vision 9",
    slug: "itel-vision-9",
    price: 129,
    os: "Android 14 Go",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    brand: "Itel",
    model: "Itel A80",
    slug: "itel-a80",
    price: 99,
    os: "Android 14 Go",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
