type Phone = {
  id: number;
  brand: string;
  model: string;
  slug: string;
  price: number;
  os: string;
  createdAt: Date;
  updatedAt: Date;
};

type Phones = Phone[];

export const dataPhones = [
  {
    id: 1,
    brand: "Apple",
    model: "iPhone 17",
    price: 1299,
    os: "iOS 19",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    brand: "Apple",
    model: "iPhone 17 Pro",
    price: 1599,
    os: "iOS 19",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    brand: "Samsung",
    model: "Galaxy S25",
    price: 1099,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    brand: "Samsung",
    model: "Galaxy S25 Ultra",
    price: 1499,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    brand: "Huawei",
    model: "Mate 70 Pro",
    price: 999,
    os: "HarmonyOS 6",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    brand: "Huawei",
    model: "P80",
    price: 899,
    os: "HarmonyOS 6",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    brand: "OPPO",
    model: "Find X8",
    price: 899,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    brand: "OPPO",
    model: "Reno 13 Pro",
    price: 599,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    brand: "Realme",
    model: "Realme GT 7",
    price: 699,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    brand: "Realme",
    model: "Realme 14 Pro",
    price: 549,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    brand: "Vivo",
    model: "Vivo X120",
    price: 999,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    brand: "Vivo",
    model: "Vivo V35",
    price: 499,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    brand: "iQOO",
    model: "iQOO 14",
    price: 799,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    brand: "iQOO",
    model: "iQOO Neo 10",
    price: 499,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    brand: "Tecno",
    model: "Tecno Phantom X4",
    price: 599,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    brand: "Tecno",
    model: "Tecno Spark 15",
    price: 199,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    brand: "Infinix",
    model: "Infinix Zero 40",
    price: 399,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    brand: "Infinix",
    model: "Infinix Note 15",
    price: 249,
    os: "Android 15",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    brand: "Itel",
    model: "Itel Vision 9",
    price: 129,
    os: "Android 14 Go",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    brand: "Itel",
    model: "Itel A80",
    price: 99,
    os: "Android 14 Go",
    releaseYear: 2025,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
